_id: "445974813257760768"
name: Test Multi-Agents
description: null
model: gpt-4o
createdAt: 2024-05-15T15:44:41.294Z
updatedAt: 2024-05-15T15:56:53.475Z
createdBy: z1VX4gakmUTP7fSTFqToQm7A2p8v1JmuB4P
updatedBy: z1VX4gakmUTP7fSTFqToQm7A2p8v1JmuB4P
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
