id: "445974813257760768"
name: Multi-Characters RPG
description: A game with multiple virtual characters.
model: gpt-4o
createdAt: 2024-05-15T15:44:41.294Z
updatedAt: 2024-06-10T06:46:20.842Z
createdBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
updatedBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
temperature: 1
topP: 1
