_id: "445974813257760768"
name: RPG
description: null
model: gpt-4o
createdAt: 2024-05-15T15:44:41.294Z
updatedAt: 2024-05-29T14:22:01.838Z
createdBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
updatedBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
